stages:
  - build_sphinx
  - deploy

build_sphinx:
  image: python:3.7-alpine
  stage: build_sphinx
  script:
  - pip install -U pip
  - pip install -r requirements.txt
  - sphinx-build -b html . public
  - sphinx-build -b latex . _latex
  artifacts:
    paths:
    - public
    - _latex
  only:
  - master
  uses: peaceiris/actions-gh-pages@v3
  if: github.ref == 'refs/heads/main'
  with:
    github_token: ${{ secrets.GH_TOKEN }}
    publish_dir: docs/build/html

pages:
  image: aergus/latex
  stage: deploy
  script:
  - cd _latex
  - make
  - mv maillageetlmentsfinis.pdf ../public/download/FEM.pdf
  artifacts:
    paths:
    - public
  only:
  - master
